import type { StoredCommerceProduct } from "./commerce-model"

export const fallbackCommerceProducts: StoredCommerceProduct[] = [
  {
    id: "commerce-fallback-silk-scarf",
    ownerId: "seed",
    name: "Silk scarf from Hangzhou",
    description: "Lightweight scarf brought back from a recent sourcing trip.",
    price: 89000,
    currency: "MNT",
    category: "Fashion",
    condition: "New",
    country: "China",
    city: "Hangzhou",
    imageUrl: "/travel-guangzhou-city-highlights.jpeg",
    sellerName: "BUKHT traveler",
    sellerContact: "",
    status: "available",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "commerce-fallback-tea-set",
    ownerId: "seed",
    name: "Porcelain travel tea set",
    description: "Compact tea set for home or office gifting.",
    price: 145000,
    currency: "MNT",
    category: "Home",
    condition: "New",
    country: "China",
    city: "Guangzhou",
    imageUrl: "/travel-yiwu-international-trade-center.jpeg",
    sellerName: "Anu",
    sellerContact: "Hidden",
    status: "available",
    createdAt: "2026-01-02T00:00:00.000Z",
    updatedAt: "2026-01-02T00:00:00.000Z",
  },
]
