"use client"
import Image from "next/image"
import { Check, LoaderCircle, Minus, Plus, ShoppingCart, Trash2, X } from "lucide-react"
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react"
import { useRouter } from "next/navigation"
import type { ApiResult, Cart } from "../../lib/commerce-types"

type CartContextValue={cart:Cart|null;loading:boolean;error:string;open:boolean;add:(productId:string,quantity?:number)=>Promise<boolean>;setOpen:(open:boolean)=>void;refresh:()=>Promise<void>}
const CartContext=createContext<CartContextValue|null>(null)
const emptyCart:Cart={id:null,items:[],totalQuantity:0,total:0,currency:"MNT"}

async function read<T>(response:Response):Promise<ApiResult<T>>{return response.json() as Promise<ApiResult<T>>}
export function CartProvider({children}:{children:React.ReactNode}){
  const router=useRouter(),[cart,setCart]=useState<Cart|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false)
  const busy=useRef(new Set<string>())
  const refresh=useCallback(async()=>{try{const response=await fetch("/api/cart",{cache:"no-store"});if(response.status===401){setCart(emptyCart);return}const body=await read<Cart>(response);if(body.success){setCart(body.data);setError("")}else setError(body.error.message)}catch{setError("Сагсны мэдээлэл ачаалсангүй.")}finally{setLoading(false)}},[])
  useEffect(()=>{void refresh();const sync=()=>void refresh();window.addEventListener("focus",sync);window.addEventListener("storage",sync);return()=>{window.removeEventListener("focus",sync);window.removeEventListener("storage",sync)}},[refresh])
  useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",close)}},[open])
  const add=useCallback(async(productId:string,quantity=1)=>{if(busy.current.has(productId))return false;busy.current.add(productId);try{const response=await fetch("/api/cart/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId,quantity})});if(response.status===401){const next=`${window.location.pathname}${window.location.search}${window.location.search?"&":"?"}cartProduct=${encodeURIComponent(productId)}`;window.location.href=`/login?next=${encodeURIComponent(next)}`;return false}const body=await read<Cart>(response);if(!body.success){setError(body.error.message);return false}setCart(body.data);setError("");localStorage.setItem("bukht-cart-sync",String(Date.now()));return true}catch{setError("Сагсанд нэмэхэд алдаа гарлаа.");return false}finally{busy.current.delete(productId)}},[])
  useEffect(()=>{const params=new URLSearchParams(window.location.search),productId=params.get("cartProduct");if(!productId)return;void add(productId).then((added)=>{if(!added)return;params.delete("cartProduct");router.replace(`${window.location.pathname}${params.size?`?${params}`:""}`)})},[add,router])
  const value=useMemo(()=>({cart,loading,error,open,add,setOpen,refresh}),[cart,loading,error,open,add,refresh])
  return <CartContext.Provider value={value}>{children}{cart?.totalQuantity?<button className="commerce-cart-fab" onClick={()=>setOpen(true)} aria-label={`Миний сагс, ${cart.totalQuantity} бараа`}><ShoppingCart/><span>{cart.totalQuantity>99?"99+":cart.totalQuantity}</span></button>:null}{open?<CartDrawer cart={cart??emptyCart} loading={loading} error={error} close={()=>setOpen(false)} update={setCart} refresh={refresh}/>:null}</CartContext.Provider>
}
export function useCart(){const value=useContext(CartContext);if(!value)throw new Error("useCart must be used inside CartProvider");return value}
export function AddToCartButton({productId,className,compact=false}:{productId:string;className?:string;compact?:boolean}){const {add}=useCart();const [state,setState]=useState<"idle"|"loading"|"done">("idle");async function click(){if(state==="loading")return;setState("loading");const added=await add(productId);setState(added?"done":"idle");if(added)window.setTimeout(()=>setState("idle"),1400)}return <button type="button" className={className} onClick={click} disabled={state==="loading"} aria-label={compact?"Сагсанд хийх":undefined}>{state==="loading"?<LoaderCircle className="is-spinning"/>:state==="done"?<Check/>:<ShoppingCart/>}{compact?null:<span>{state==="done"?"Сагсанд нэмэгдлээ":"Сагсанд хийх"}</span>}</button>}

function CartDrawer({cart,loading,error,close,update,refresh}:{cart:Cart;loading:boolean;error:string;close:()=>void;update:(cart:Cart)=>void;refresh:()=>Promise<void>}){
 const [pending,setPending]=useState(new Set<string>()),[checkout,setCheckout]=useState(false),[notice,setNotice]=useState("");const panel=useRef<HTMLElement>(null)
 useEffect(()=>{panel.current?.focus()},[])
 async function mutate(itemId:string,method:"PATCH"|"DELETE",quantity?:number){if(pending.has(itemId))return;setPending(current=>new Set(current).add(itemId));try{const response=await fetch(`/api/cart/items/${itemId}`,{method,headers:{"Content-Type":"application/json"},body:method==="PATCH"?JSON.stringify({quantity}):undefined});const body=await read<Cart>(response);if(body.success){update(body.data);localStorage.setItem("bukht-cart-sync",String(Date.now()))}else setNotice(body.error.message)}finally{setPending(current=>{const next=new Set(current);next.delete(itemId);return next})}}
 async function checkoutNow(){setCheckout(true);setNotice("");try{const response=await fetch("/api/checkout",{method:"POST"});const body=await read<{id:string;paymentConfigured:boolean}>(response);setNotice(body.success?`Захиалгын ноорог #${body.data.id.slice(0,8)} үүслээ. Төлбөрийн үйлчилгээ холбогдоогүй байна.`:body.error.message)}finally{setCheckout(false)}}
 return <div className="commerce-overlay" onMouseDown={(event)=>{if(event.target===event.currentTarget)close()}}><aside ref={panel} className="commerce-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title" tabIndex={-1}><header><h2 id="cart-title">Миний сагс</h2><button onClick={close} aria-label="Сагс хаах"><X/></button></header><div className="commerce-cart-list">{loading?<p>Ачаалж байна...</p>:error?<div className="commerce-state"><p>{error}</p><button onClick={()=>void refresh()}>Дахин оролдох</button></div>:!cart.items.length?<div className="commerce-state"><ShoppingCart/><p>Таны сагс хоосон байна.</p></div>:cart.items.map(item=><article className="commerce-cart-item" key={item.id}>{item.imageUrl?<Image src={item.imageUrl} alt="" width={72} height={72} unoptimized/>:<div className="commerce-cart-placeholder"><ShoppingCart/></div>}<div><strong>{item.name}</strong>{item.sellerName?<small>{item.sellerName}</small>:null}<span>{item.formattedPrice}</span>{!item.available?<em>Бараа ашиглах боломжгүй болсон.</em>:null}<div className="commerce-quantity"><button disabled={pending.has(item.id)} onClick={()=>void mutate(item.id,item.quantity===1?"DELETE":"PATCH",item.quantity-1)} aria-label="Тоо хасах"><Minus/></button><b>{item.quantity}</b><button disabled={pending.has(item.id)||item.quantity>=99} onClick={()=>void mutate(item.id,"PATCH",item.quantity+1)} aria-label="Тоо нэмэх"><Plus/></button><button className="is-delete" disabled={pending.has(item.id)} onClick={()=>void mutate(item.id,"DELETE")} aria-label="Устгах"><Trash2/></button></div></div><strong>{format(item.subtotal,item.currency)}</strong></article>)}</div><footer><div><span>Нийт {cart.totalQuantity} ширхэг</span><strong>{cart.currency==="MIXED"?"Олон валют":format(cart.total,cart.currency)}</strong></div>{notice?<p>{notice}</p>:null}<button className="commerce-checkout" disabled={!cart.items.length||cart.items.some(item=>!item.available)||checkout} onClick={()=>void checkoutNow()}>{checkout?<LoaderCircle className="is-spinning"/>:null}Төлбөрийн хэсэгт үргэлжлүүлэх</button></footer></aside></div>
}
function format(value:number,currency:string){return `${new Intl.NumberFormat("mn-MN").format(value)} ${currency}`}
